name: Backend CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          # Note: be aware of specific Python versions. This version should always
          # match what version we specif in our other setup files, like start_backend.sh.
          # 3.6.9 started breaking GitHub actions, see related issue:
          # https://github.com/actions/setup-python/issues/162#issuecomment-1324176396
          python-version: 3.8
      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          cd backend
          make install
      - name: Lint with flake8
        run: |
          cd backend
          make lint
      - name: Run tests
        run: |
          cd backend
          # make test
          python3 manage.py test climateconnect_api.tests.test_user_views.TestSignUpView.test_signup_api_success
