name: Python linting
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11
          cache: true
          cache-dependency-path: |
            ./backend/pdm.lock
      - name: Run Black
        uses: psf/black@stable
        with:
          src: backend
      # Include `--format=github` to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --format=github backend
      - name: Install dependencies
        run: pdm sync
        working-directory: backend
      - name: Run Mypy
        run: pdm run mypy .
        working-directory: backend
